name: CI-CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - run: |
          echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
          mkdir -p .cache
        
      - name: Cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          
      - name: Build mkdocs
        run: mkdocs gh-deploy --force

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: deploy
        env:
          SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
          SERVER: "nikki@celery.icu"
          REMOTE_PATH: "/var/www/gh-pages/"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
          
          rsync -avz --delete --exclude='.*' -e "ssh -i ~/.ssh/deploy_key" . $SERVER:$REMOTE_PATH

          rm -rf ~/.ssh/deploy_key